version: '2'
services:
  namesrv:
    image: registry.silot.tech/common/apacherocketmq:4.5.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - /docker/rocketmq/data/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv
  broker:
    image: registry.silot.tech/common/apacherocketmq:4.5.0
    container_name: rmqbroker
    links:
      - namesrv
    ports:
      - 10909:10909
      - 10911:10911
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - /docker/rocketmq/data/broker/logs:/home/rocketmq/logs
      - /docker/rocketmq/data/broker/store:/home/rocketmq/store
      - /docker/rocketmq/data/broker/conf/broker.conf:/opt/rocketmq-4.5.0/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-4.5.0/conf/broker.conf
  rocketmq-console:
    image: styletang/rocketmq-console-ng:latest
    depends_on:
        - broker
    ports:
        - 18080:8080
    environment:
      - NAMESRV_ADDR=namesrv:9876
